spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Producer: Protobuf + Schema Registry + TopicNameStrategy
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
# Schema Registry
spring.kafka.properties.schema.registry.url=http://localhost:8081
spring.kafka.properties.auto.register.schemas=false
spring.kafka.properties.use.latest.version=true
spring.kafka.properties.value.subject.name.strategy=io.confluent.kafka.serializers.subject.TopicNameStrategy
spring.kafka.properties.specific.protobuf.value.type=com.kafka.patterns.proto.OutboxOrderEvent
spring.kafka.producer.properties.compression.type=lz4

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always