# stage 1: build native-image using GraalVM (build machine must have Graal or use graalvmci images)
FROM ghcr.io/graalvm/native-image-community:24.0.1 as builder
WORKDIR /workspace
COPY . /workspace
RUN microdnf install maven && \
    mvn -DskipTests clean native:compile

# stage 2: runtime
FROM busybox:glibc
COPY --from=builder /workspace/payments-service/target/payments-service .
EXPOSE 8080
ENTRYPOINT ["/payments-service"]